In [1]:
from sklearn.cluster import KMeans
import numpy as np
import random
import matplotlib.pyplot as plt

In [125]:
class Graph:
    def __init__(self, maps, edgenum=0):
        self.map = maps
        self.nodenum = len(maps)
        self.edgenum = edgenum
        self.W = np.zeros((len(maps), len(maps)))#maps
        self.path = np.zeros((len(maps), len(maps)))
        self.W_Bellman_Ford = np.zeros((len(maps), len(maps)))
        self.path_Bellman_Ford = np.zeros((len(maps), len(maps)))
        self.edge = []
        e = []
        for i in range(self.nodenum):
            for j in range(self.nodenum):
                if(self.map[i][j] != 0):
                    e.append(i)
                    e.append(j)
                    e.append(self.map[i][j])
                    e1 = e[:] 
                    self.edge.append(e1)
                e[:] = []

    def isOutRange(self, x):
        try:
            if x >= self.nodenum or x <= 0:
                raise IndexError
        except IndexError:
            print("We have errors everyday, don't worry, check index again!")

    def GetNodenum(self):
        self.nodenum = len(self.map)
        return self.nodenum

    def GetEdgenum(self):
        self.edgenum = 0
        for i in range(self.nodenum):
            for j in range(self.nodenum):
                if self.map[i][j] != 0:
                    self.edgenum = self.edgenum + 1
        return self.edgenum

    def InsertNode(self):
        for i in range(self.nodenum):
            self.map[i].append(0)
            self.W[i].append(0)
            self.path.append(0)
        self.nodenum = self.nodenum + 1
        ls = [0] * self.nodenum
        self.map.append(ls)
        self.W.append(ls)
        self.path.append(ls)

    def DeleteNode(self, x):
        for i in range(self.nodenum):
            if self.map[i][x] != 0:
                self.map[i][x] = 0
                self.edgenum = self.edgenum - 1
            if self.map[x][i] != 0:
                self.map[x][i] = 0
                self.edgenum = self.edgenum - 1

    def AddEdge(self, x, y):
        if self.map[x][y] != 1:
            self.map[x][y] = 1
            self.edgenum = self.edgenum + 1

    def RemoveEdge(self, x, y):
        if self.map[x][y] != 0:
            self.map[x][y] = 0
            self.edgenum = self.edgenum - 1

    def BreadthFirstSearch(self):
        def BFS(self, i):
            print(i)
            visited[i] = 1
            for k in range(self.nodenum):
                if self.map[i][k] == 1 and visited[k] == 0:
                    BFS(self, k)
        visited = [0] * self.nodenum
        for i in range(self.nodenum):
            if visited[i] is 0:
                BFS(self, i)

    def DepthFirstSearch(self):
        def DFS(self, i, queue):
            queue.append(i)
            print(i)
            visited[i] = 1
            if len(queue) != 0:
                w = queue.pop()
                for k in range(self.nodenum):
                    if self.map[w][k] is 1 and visited[k] is 0:
                        DFS(self, k, queue)
        visited = [0] * self.nodenum
        queue = []
        for i in range(self.nodenum):
            if visited[i] is 0:
                DFS(self, i, queue)

    def K_Nearest_Neighbor_Similarity_Matrix_Computr(self, k):
        remain = [0] * k
        for row in range(self.nodenum):
            for i in range(k):
                remain[i] = row + i +1
            min_index = remain[0]
            for j in range(1, k):
                if(self.map[row][remain[j]] <= self.map[row][remain[0]]):
                    min_index = remain[j]
            col = row + k + 1
            while col%self.nodenum != row:
                if(self.map[row][col] > self.map[row][min_index]):
                    self.map[row][min_index] = 0
                    min_index = col

                    for j in range(k):
                        if(self.map[row][remain[j]] <= self.map[row][min_index]):
                            min_index = remain[j]
                else:
                    self.map[row][col] = 0

        for row in range(self.nodenum):
            for col in range(self.nodenum):
                if(self.map[row][col] != self.map[col][row]):
                    if(self.map[row][col] != 0):
                        self.map[col][row] = self.map[row][col]
                    if(self.map[col][row] != 0):
                        self.map[row][col] = self.map[col][row]
        pass

    def Bellman_Ford(self, original):
        for i in range(self.nodenum):
            if i == original:
                self.W_Bellman_Ford[original][i] = 0
            else:
                self.W_Bellman_Ford[original][i] = 1000000 # max
            if self.map[original][i] != 0:
                self.W_Bellman_Ford[original][i] = self.map[original][i]
                self.path_Bellman_Ford[original][i] = original
            else:
                self.path_Bellman_Ford[original][i] = -1

        for j in range(self.nodenum):
            flag_end = False
            for e in range(len(self.edge)):
                if self.W_Bellman_Ford[original][(self.edge[e])[1]] > self.W_Bellman_Ford[original][(self.edge[e])[0]] + (self.edge[e])[2]:
                    self.W_Bellman_Ford[original][(self.edge[e])[1]] = self.W_Bellman_Ford[original][(self.edge[e])[0]] + (self.edge[e])[2]
                    self.path_Bellman_Ford[original][(self.edge[e])[1]] = (self.edge[e])[0]
                    flag_end = True
            if(flag_end == False):
                break

        flag = True 
        for e1 in range(len(self.edge)):
            if self.W_Bellman_Ford[original][(self.edge[e1])[1]] > self.W_Bellman_Ford[original][(self.edge[e1])[0]] + (self.edge[e1])[2]:
                flag = False
                break
        return flag
    
    def SimilarityMatrix(self):
        for row in range(self.nodenum):
            for col in range(self.nodenum):
                self.W[row][col] = self.map[row][col]
                if(self.map[row][col] != 0 and row != col):
                    self.path[row][col] = row
                else:
                    self.path[row][col] = -1
        for k in range(self.nodenum):
            for i in range(self.nodenum):
                for j in range(self.nodenum):
                    if(self.W[i][k] != 0 and self.W[k][j] != 0):
                        if((self.W[i][k] + self.W[k][j] < self.W[i][j]) or (self.W[i][j] == 0 and i != j)): # 0表示不通或者无穷大
                            self.W[i][j] = self.W[i][k] + self.W[k][j]
                            self.path[i][j] = self.path[k][j]
                            

<>:80: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:96: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:80: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:96: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-125-d3d55cb76bcf>:80: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if visited[i] is 0:
<ipython-input-125-d3d55cb76bcf>:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.map[w][k] is 1 and visited[k] is 0:
<ipython-input-125-d3d55cb76bcf>:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.map[w][k] is 1 and visited[k] is 0:
<ipython-input-125-d3d55cb76bcf>:96: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if visited[i] is 0:


In [126]:
def getWbyKNN(dis_matrix, k):
        print(type(dis_matrix))
        W = np.zeros((len(dis_matrix), len(dis_matrix)))
        for idx,each in enumerate(dis_matrix):
            index_array  = np.argsort(each)
            for i in index_array[1:k+1]:
                W[idx][i] = dis_matrix[idx][i] 
        tmp_W = np.transpose(W)
        W = (tmp_W+W)/2 
        return W

In [127]:
def distance(x, y):
    return  np.linalg.norm(x-y)

In [128]:
#Degree matrix 
def degreeMatrix(W):
    points_num = len(W)
    D = np.diag(np.zeros(points_num))
    for i in range(points_num):
        D[i][i] = sum(W[i])
    return D

In [129]:
def eigenvector(L, cluster_num):
    eigval,eigvec = np.linalg.eig(L)
    dim = len(eigval)
    dictEigval = dict(zip(eigval,range(0,dim)))
    kEig = np.sort(eigval)[0:cluster_num]
    ix = [dictEigval[k] for k in kEig]
    return eigval[ix],eigvec[:,ix]

In [130]:
def SimilarityMatrix(W):
        M = np.zeros((len(W), len(W)))
        for i in range(len(W)):
            for j in range(len(W)):
                if W[i][j] != 0:
                    M[i][j] = 1 / W[i][j]
        return M

In [131]:
def SpectralClustering():

    maps = [
        [0, 3, 5, 8, 0],
        [3, 0, 6, 4, 11],
        [5, 6, 0, 2, 0],
        [8, 4, 2, 0, 10],
        [0, 11, 0, 10, 0]
    ]
    
    G = Graph(maps)
    print(G.map)
    G.SimilarityMatrix()
    W1 = G.W
    print(W1)
    path = G.path
    print(path)

    M = SimilarityMatrix(W1)

    W = getWbyKNN(M, 2)             # k=2
    D = getD(W)
    print(W)
    print(D)

    # Laplacian
    L = D - W
    cluster_num = 3                 # cluster = 3

    eigval, eigvec = eigenvector(L, cluster_num)

    clf = KMeans(n_clusters=cluster_num)
    s = clf.fit(eigvec)
    C = s.labels_
    print(C)

In [132]:
def DoTest():
    maps = [
        [0, 3, 5, 8, 0],
        [3, 0, 8, 4, 11],
        [5, 6, 0, 2, 0],
        [8, 4, 2, 0, 10],
        [0, 11, 0, 10 , 0]
        ]
    G = Graph(maps)
    print(G.map)
    G.SimilarityMatrix()
    W = G.W
    path = G.path
    print(path)
    print(W)

    for i in range(G.nodenum):
        G.Bellman_Ford(i)
    W1 = G.W_Bellman_Ford
    path1 = G.path_Bellman_Ford
    print(W1)
    print(path1)
    M = SimilarityMatrix(W)
    print(M)

In [133]:
DoTest()

[[0, 3, 5, 8, 0], [3, 0, 8, 4, 11], [5, 6, 0, 2, 0], [8, 4, 2, 0, 10], [0, 11, 0, 10, 0]]
[[-1.  0.  0.  1.  1.]
 [ 1. -1.  3.  1.  1.]
 [ 2.  2. -1.  2.  3.]
 [ 1.  3.  3. -1.  3.]
 [ 1.  4.  3.  4. -1.]]
[[ 0.  3.  5.  7. 14.]
 [ 3.  0.  6.  4. 11.]
 [ 5.  6.  0.  2. 12.]
 [ 7.  4.  2.  0. 10.]
 [14. 11. 12. 10.  0.]]
[[ 0.  3.  5.  7. 14.]
 [ 3.  0.  6.  4. 11.]
 [ 5.  6.  0.  2. 12.]
 [ 7.  4.  2.  0. 10.]
 [14. 11. 12. 10.  0.]]
[[-1.  0.  0.  1.  1.]
 [ 1. -1.  3.  1.  1.]
 [ 2.  2. -1.  2.  3.]
 [ 1.  3.  3. -1.  3.]
 [ 1.  4.  3.  4. -1.]]
[[0.         0.33333333 0.2        0.14285714 0.07142857]
 [0.33333333 0.         0.16666667 0.25       0.09090909]
 [0.2        0.16666667 0.         0.5        0.08333333]
 [0.14285714 0.25       0.5        0.         0.1       ]
 [0.07142857 0.09090909 0.08333333 0.1        0.        ]]


In [134]:
'''
Ask professor
1. about complexity clustering algos, hierarchical clustering/spectral clustering/kmeans/divisive
2. time processing
3. the kmeans algorithm could be modified to generate more than one random mean for each cluster,
allowing it to run in multiple threads at the same time?
4. could or couldn't initialize graph like a "class"
5. Closed neighborhood similarity or Dijsktra
'''

'\nAsk professor\n1. about complexity clustering algos, hierarchical clustering/spectral clustering/kmeans/divisive\n2. time processing\n3. the kmeans algorithm could be modified to generate more than one random mean for each cluster,\nallowing it to run in multiple threads at the same time?\n4. could or couldn\'t initialize graph like a "class"\n5. Closed neighborhood similarity or Dijsktra\n'

In [135]:
SpectralClustering()

[[0, 3, 5, 8, 0], [3, 0, 6, 4, 11], [5, 6, 0, 2, 0], [8, 4, 2, 0, 10], [0, 11, 0, 10, 0]]
[[ 0.  3.  5.  7. 14.]
 [ 3.  0.  6.  4. 11.]
 [ 5.  6.  0.  2. 12.]
 [ 7.  4.  2.  0. 10.]
 [14. 11. 12. 10.  0.]]
[[-1.  0.  0.  1.  1.]
 [ 1. -1.  1.  1.  1.]
 [ 2.  2. -1.  2.  3.]
 [ 1.  3.  3. -1.  3.]
 [ 1.  4.  3.  4. -1.]]
<class 'numpy.ndarray'>
[[0.         0.         0.         0.14285714 0.07142857]
 [0.         0.         0.16666667 0.         0.04545455]
 [0.         0.16666667 0.         0.         0.08333333]
 [0.14285714 0.         0.         0.         0.05      ]
 [0.07142857 0.04545455 0.08333333 0.05       0.        ]]
[[0.21428571 0.         0.         0.         0.        ]
 [0.         0.21212121 0.         0.         0.        ]
 [0.         0.         0.25       0.         0.        ]
 [0.         0.         0.         0.19285714 0.        ]
 [0.         0.         0.         0.         0.25021645]]
[0 1 1 0 2]
